### PR TITLE
Add TPC-DS scripts and documentation

### PR DESCRIPTION
**Pull request by andygrove**
Adds some scripts and documentation to help with generating TPC-DS data sets.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Testing these out today, will let you know how it goes! :)

**Comment by mbutrovich** [comment]
Data generation ran successfully for SF 100. I'll try with SF 10 and SF 1, but that's an approval from me!

**Comment by mbutrovich** [comment]
SF10 was good too.

**Review by kazuyukitanimura — APPROVED** [review]
LGTM

**Comment by andygrove** [comment]
Thanks @kazuyukitanimura and @mbutrovich

**Pull request merged**
